### PR TITLE
Coal alloy furnace ABM: tolerate broken metadata

### LINKED ISSUE #398: recipes.lua:62: bad argument #1 to 'ipairs' (table expected, got nil)
If a coal ("fuel-fired", whatever) alloy furnace is missing its inventory data, the ABM that runs these machines crashes.

Example output:
```
ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'technic' in callback LuaABM::trigger(): .../worldmods/technic/technic/machines/register/recipes.lua:62: bad argument #1 to 'ipairs' (table expected, got nil)
ERROR[Main]: stack traceback:
ERROR[Main]: 	[C]: in function 'ipairs'
ERROR[Main]: 	.../worldmods/technic/technic/machines/register/recipes.lua:62: in function 'get_recipe_key'
ERROR[Main]: 	.../worldmods/technic/technic/machines/register/recipes.lua:70: in function 'get_recipe'
ERROR[Main]: 	...ds/technic/technic/machines/other/coal_alloy_furnace.lua:129: in function 'func'
```

While this was initially discovered as a result of map corruption, it is easy to reproduce without a corrupted map:
1. Place `technic:coal_alloy_furnace` with WorldEdit (`//s technic:coal_alloy_furnace`)
2. Server will crash within approximately 1 second

### PR DESCRIPTION
**Pull request by S-S-X**
Closes #398 

For API `technic.get_recipe(method, items)` I'd rather leave it as is and not try to check every possible user mistake there but rather specify that arguments must be of correct type and contain correct information.

This old compatibility shim has been there for over 11 years already and now it has been removed.
Additionally we've already dropped some similar compatibility shims that were not even this old.
```lua
		if inv:get_size("src") == 1 then -- Old furnace -> convert it
			inv:set_size("src", 2)
			inv:set_stack("src", 2, inv:get_stack("src2", 1))
			inv:set_size("src2", 0)
		end
```

Fixes:
```
Failure → spec/other_spec.lua @ 45
  Coal alloy furnace wont crash without placement callbacks
  spec/other_spec.lua:48: Expected no error, but caught:
```

### CODE REVIEW

File: technic/machines/other/coal_alloy_furnace.lua [hunk 1]
```diff
@@ -189,13 +187,8 @@ minetest.register_abm({
...
-		local fuel = nil
-		local afterfuel
 		local fuellist = inv:get_list("fuel")
-
-		if fuellist then
-			fuel, afterfuel = minetest.get_craft_result({method = "fuel", width = 1, items = fuellist})
-		end
+		local fuel, afterfuel = minetest.get_craft_result({method = "fuel", width = 1, items = fuellist})
 
 		if fuel.time <= 0 then
```
Comment (S-S-X) [inline technic/machines/other/coal_alloy_furnace.lua:193]: **Kind of seems too simple to me, did I overlook something?**

Reasoning: in case `if fuellist` expression fails then it would anyway crash on `if fuel.time <= 0` so basically this shouldn't really affect outcome and is basically just cleanup.

I believe this should be fine and there's other issues unrelated to this change in case it actually crashes.
