### PR TITLE
Fix and improve max_lag

### LINKED ISSUE #166: Fix max_lag stuff
Must be fixed if this gets merged https://github.com/minetest/minetest/pull/11077
Should be fixed anyway even if above does not get merged.

Not technically bug yet... there was no wanna-be-bug label...

Stuff that must be "fixed" is here:
https://github.com/mt-mods/technic/blob/master/technic/max_lag.lua

### PR DESCRIPTION
**Pull request by OgelGames**
Lag is now calculated inside the mod, instead of being extracted from server status.

Fixes #166 and #191

### CODE REVIEW

File: technic/lag.lua [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+function technic.get_avg_lag()
+	if #samples < 1 then
+		return 0
+	end
+	local avg_lag = 0
+	for _,t in pairs(samples) do
+		avg_lag = avg_lag + t
+	end
+	return avg_lag / #samples
+end
```
Comment (S-S-X) [inline technic/lag.lua]: Where these functions are useful in technic? Just my opinion, I think these are not needed and seems to be there just to make technic API provide generic library functions. Consider removing both get_min_lag and get_avg_lag unless there's immediate use for these.

Comment (OgelGames) [reply technic/lag.lua]: The timing...

**Comment by S-S-X** [comment]
If going for average then is it possible to use https://github.com/mt-mods/technic/blob/fd4bece11a633e665cf73c782bb1d2032169ee88/technic/machines/network.lua#L382-L394 which already exists and almost sure outperforms anything else when it comes to overhead of calculating averages?
It might be possible to drop max_lag.lua/lag.lua completely while reducing total lines of code and increasing performance.

However if it seems that doing it will require changes to sma function then probably should not be done as it can actually benefit from performance somewhat while lag.lua functions executed only once / globalstep wont benefit that much.

**Comment by OgelGames** [comment]
I don't think that should be used in this case, the method I used aims to avoid calculations being done every globalstep, and instead they are only done when the functions are called (which is no more than once a second).

File: technic/lag.lua [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+	end
+end)
+
+
+function technic.get_max_lag()
+	if #samples < 1 then
+		return 0
+	end
+	local max_lag = 0
+	for _,t in pairs(samples) do
```
Comment (S-S-X) [inline technic/lag.lua:23]: There to squeeze every bit of performance out of loop you can use ipairs over pairs because samples is quaranteed to be always indexed without holes.

File: technic/lag.lua [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+	end
+	return max_lag
+end
+
+function technic.get_avg_lag()
+	if #samples < 1 then
+		return 0
+	end
+	local avg_lag = 0
+	for _,t in pairs(samples) do
```
Comment (S-S-X) [inline technic/lag.lua:36]: Same here as previous to squeeze every bit of performance out of loop you can use ipairs over pairs because samples is quaranteed to be always indexed without holes.

**Comment by S-S-X** [comment]
> I don't think that should be used in this case, the method I used aims to sample every globalstep, while avoiding calculations being done every globalstep; instead they are only done when the functions are called (which is no more than once a second).

Yes, I think that fact makes it better to have separate function that calculates average for whole table instead of rolling average calculated for single added value is probably better even while table does contain 100 entries and average globalstep is only about 100ms favoring per value calculation more vs per call calculation cost but I think not enough to warrant changing it.

Also if someone wants to make average for get_avg_lag based only 10 values then globalstep continuous would be worse and only benefit would be from spereading (very small) workload over longer time.

**Comment by BuckarooBanzay** [comment]
ok, this is nicer than my ugly hack :+1: 
Just a heads-up: the `dtime` value may never exceed 2 seconds: https://github.com/minetest/minetest/blob/e9bc59e376f88f1d4d1c6d3fedf62d9049e3e60d/src/server.cpp#L524-L526

**Review by BuckarooBanzay — APPROVED** [review]

**Comment by OgelGames** [comment]
> the `dtime` value may never exceed 2 seconds

That's strange... Explains this though: https://github.com/minetest-monitoring/monitoring/blob/master/builtin/lag.lua#L28-L30

**Comment by S-S-X** [comment]
Tested a bit, generated 5 seconds artificial globalstep lag (busy loop in globalstep) and checked how this responds.
Engine 4.9 seconds lag reported.
Technic.get_avg_lag 0.158 seconds lag reported.

Multiple 15 seconds lag spikes, bit over 0.2 seconds reported by technic.get_avg_lag and engine reporting just bit less than 15 seconds lag.

This will change completely how technic globalstep lag check mechanism will actually respond to different lag spikes, it might be fine or it might need some adjustments.
Maybe still make it respond bit faster by reducing size of table where values are collected, some 20 - 50 possibly?

Still remember that what I tested was probably not anywhere near any real situation but it still shows that response is maybe bit too slow especially compared to previous instant response.
Reducing table size will also affect similar way when reducing high averages back to normal when actual globalstep lag gets down, response is faster and technic globalstep frequency gets higher bit sooner when lag is over.

As averages are collected over very long time it does not really detect high lag spikes.

**Comment by S-S-X** [comment]
For actual server testing maybe it could be useful to add current average lag values to output of command, possibly just add another value for technic.get_avg_lag here:
https://github.com/mt-mods/technic/blob/64237957e472c35c81e257ed59026500098808ee/technic/machines/init.lua#L96-L99

So that running `/technic_get_active_networks` would say something like:
```
Cached network data: 2 active networks, 4 total networks, 16 network nodes, 0.256s avg lag

... network data report rows ...
```

**Comment by OgelGames** [comment]
> Tested a bit, generated 5 seconds artificial globalstep lag (busy loop in globalstep) and checked how this responds.
> Engine 4.9 seconds lag reported.
> Technic.get_avg_lag 0.158 seconds lag reported.

Hmm... maybe the method MT uses is better, but then that is a bit too slow to return back to normal after a short lag spike... 🤔

**Comment by S-S-X** [comment]
> Hmm... maybe the method MT uses is better, but then that is a bit too slow to return back to normal after a short lag spike..

Yes, I think this new system is a lot better as max_lag returned by engine will take extremely long time to go down if it gets high enough.
But some tuning is needed as it should really also get higher a lot faster, simplest way to make it do that (and also even return back to normal faster when lag is over) is to reduce table size making single value to affect average a lot more.

Other way to add faster response would be to scale added values by multiplying  input (and counter this accordingly when reading averages), that makes higher values more significant.

Or calculate averages by using only say 10 highest values which would account more for short lag spikes, might or might not be useful... this could also be tuned for example to drop 40 highest and 40 lowest values and use 20 remaining to calculate average.

**Comment by OgelGames** [comment]
Maybe this would work? It's basically the same as the way the engine calculates max_lag, but it decreases faster. (`* 0.9` instead of `* 0.9998`)
```lua
local last_step = minetest.get_us_time()

local max_lag = 0

minetest.register_globalstep(function()
	-- Calculate own dtime as a workaround to 2 second limit
	local now = minetest.get_us_time()
	local dtime = now - last_step
	last_step = now
	
	max_lag = max_lag * 0.9  -- Decrease slowly
	
	if dtime > max_lag then
		max_lag = dtime
	end
end)


function technic.get_max_lag()
	return max_lag / 1000000
end
```
Could also tie that multiplier to a setting too... 🤔

**Comment by S-S-X** [comment]
> Maybe this would work? It's basically the same as the way the engine calculates max_lag, but it decreases faster. (`* 0.9` instead of `* 0.9998`)

I think this would work fine, better than what engine does anyway. I however liked average values bit more however as it would smooth out occasional single server step lag spikes while still providing very useful averages.

For useful averages you don't really need many values to do that, network lag detection did it very with just 3 values but still used 5 values (no specific reason for 5 values... it was just largest where I was not able to measure performance with get_us_time at all).

> Could also tie that multiplier to a setting too... 🤔

Yes, would be good idea to allow easier adjustment.

**Comment by OgelGames** [comment]
So I decided the only way to figure out this properly was to test the different methods, and plot them on a graph:

* Orange = `max_lag` from the engine (pulled from server status),
* Green = `technic.get_max_lag()` in this PR
* Blue = `technic.get_avg_lag()` in this PR
* Red = `max_lag` calculated with a multiplier of 0.99.

lag-graph
https://app.rawgraphs.io/

You were definitely right about `technic.get_avg_lag()` not responding to lag spikes... 👀

File: technic/max_lag.lua [hunk 4]
```diff
@@ -1,15 +1,23 @@
...
-        local t={}
-        local i=0
-        for k in string.gmatch(input,"([^"..sep.."]+)") do
-            t[i]=k
-            i=i+1
-        end
-        return t
-end
+
+local multiplier = tonumber(technic.config:get("max_lag_reduction_multiplier")) or 0.99
```
Comment (S-S-X) [inline technic/max_lag.lua:2]: You could also use `technic.config:get_int("max_lag_reduction_multiplier")` here, name should actually be get_number or something like that.
Benefit is that you do not hardcode defaults in code file but in config.lua (and as lesser benefit it validates key during CI tests).

**Comment by S-S-X** [comment]
> So I decided the only way to figure out this properly was to test the different methods, and plot them on a graph:

Did not test in game again but I think this can be merged. While it does not provide any smoothing for very short lag spikes looking at graphs you provided this is clearly way better for technic lag control purposes than engine status parsing and it responds to lag spikes immediately just like engine status parsing did.

Maybe I'll add lag value to network stats command, not exactly required but can still be useful to confirm in game what is happening.
