### PR TITLE
Fix cable plate placing on several-blocks nodes

### LINKED ISSUE #305: nil index with cable plate
```
AsyncErr: Lua: Runtime error from mod 'technic' in callback item_OnPlace(): table index is nil
stack traceback:
	[C]: in function 'rawset'
	.../20220909_2250/minetest/bin/../builtin/common/vector.lua:21: in function '__newindex'
	...bin/../mods/technic/technic/machines/register/cables.lua:102: in function <...bin/../mods/technic/technic/machines/register/cables.lua:94>
```

I ran into this when placing a cable plate on top of a travelnet.
(I was doing /area_pos set and missed a node, had a cable plate in hand so tried to place that)

possibly a travelnet top node issue. possibly good to fix here as there may be other such nodes.

### PR DESCRIPTION
**Pull request by Athozus**
The description is not very well because it's hard to describe what I've done in a single, notably in English. I can force-push to a better commit message if needed. EDIT : I think the title describe better the changes now.

What I've done : 
* I noticed by debugging with `minetest.chat_send_all` that the `index` value was exceeding the range of #xyz, so it caused `nil` index in `fine_pointed` call.
* So I just add "brought back" the `index` value within the range of 3 divisors. Lua starts numbering at `1`, so it does that weird `(index-1)%3+1`

Fix #305

### CODE REVIEW

**Comment by S-S-X** [comment]
@Athozus can you test these in game?
```
Failure → spec/nodes_spec.lua @ 157
Technic node placement cable plates middle aux1 placement heading X+
spec/nodes_spec.lua:162: Expected objects to be equal.
Passed in:
(string) 'technic:hv_cable_plate_4'
Expected:
(string) 'technic:hv_cable_plate_1'

Failure → spec/nodes_spec.lua @ 166
Technic node placement cable plates middle aux1 placement heading Y+
spec/nodes_spec.lua:171: Expected objects to be equal.
Passed in:
(string) 'technic:hv_cable_plate_5'
Expected:
(string) 'technic:hv_cable_plate_2'

Failure → spec/nodes_spec.lua @ 232
Technic node placement cable plates aux1 placement pointing Z+ edge heading X+
spec/nodes_spec.lua:237: Expected objects to be equal.
Passed in:
(string) 'technic:hv_cable_plate_4'
Expected:
(string) 'technic:hv_cable_plate_6'

Failure → spec/nodes_spec.lua @ 240
Technic node placement cable plates aux1 placement pointing Z+ edge heading Y+
spec/nodes_spec.lua:245: Expected objects to be equal.
Passed in:
(string) 'technic:hv_cable_plate_5'
Expected:
(string) 'technic:hv_cable_plate_6'
```

**Comment by Athozus** [comment]
> However, does it need other than normalization of fine_pointed vector (or pointed_thing.above)? That would be cleaner as there's `vector.normalize(v)`. And should deliver exact same results.

`index` is a number, so I don't understand why `vector.normalize()` should be used. Note that `fine_pointed` is constituted of `nil` values, not `0` (like I except from the function, according to [the documentation](https://github.com/minetest/minetest/blob/master/doc/lua_api.md#common-functions-and-methods)).

**Comment by S-S-X** [comment]
> `index` is a number, so I don't understand why `vector.normalize()` should be used. Note that `fine_pointed` is constituted of `nil` values, not `0` (like I except from the function, according to [the documentation](https://github.com/minetest/minetest/blob/master/doc/lua_api.md#common-functions-and-methods)).

Basically what you're doing is normalization afterwards. Normalizing beforehand is just another way to do the same.
Reason why I'm suggesting vector.normalize is that it would be kinda self explaining and cleaner in code.

But I guess, whether going with current way for normalization or using vector.normalize, it probably would be good to also add comment that explains corner case why it has to be normalized.

File: technic/machines/register/cables.lua [hunk 1]
```diff
@@ -103,7 +103,9 @@ function technic.register_cable_plate(nodename, data)
 				if (crtl.aux1 or crtl.sneak) and not (crtl.aux1 and crtl.sneak) and index ~= 0 then
 					local fine_pointed = minetest.pointed_thing_to_face_pos(placer, pointed_thing)
 					fine_pointed = vector.subtract(fine_pointed, pointed_thing.above)
-					fine_pointed[xyz[index < 0 and -index or index]] = nil
+					index = index < 0 and -index or index
+					index = (index-1)%3+1
```
Comment (S-S-X) [inline technic/machines/register/cables.lua:107]: Comment could possibly be
```suggestion
					-- Normalize direction to prevent `xyz` index overflow with oversize nodes
					index = (index-1)%3+1
```

**Comment by S-S-X** [comment]
Did read whole thing again and to handle all cases wouldn't it be required to normalize way before current solution, on line 99:
```lua
local pointed_thing_diff = vector.subtract(pointed_thing.above, pointed_thing.under)
```
Change to
```lua
local pointed_thing_diff = vector.normalize(vector.subtract(pointed_thing.above, pointed_thing.under))
```
Wouldn't that make sure it is handled in all possible corner cases, make it bit more cleaner / understandable and also shorter?

**Comment by Athozus** [comment]
> Actually there's even better shorthand method for it (documented since 5.0.0):
> 
> ```lua
> local pointed_thing_diff = vector.direction(pointed_thing.above, pointed_thing.under)
> ```
> 
> `fine_pointed` still needs the same. I think going from `vector.subtract` to `vector.direction` should work fine there as well.

Replacing `subtract` by `direction` causes strange behaviours. Notably different results while pressing `Sneak` or not pressing it on « normal » blocks.

**Comment by S-S-X** [comment]
> Replacing `subtract` by `direction` causes strange behaviours. Notably different results while pressing `Sneak` or not pressing it on « normal » blocks.

Checked this, try with:
```lua
local pointed_thing_diff = vector.direction(pointed_thing.under, pointed_thing.above)
```
and
```lua
fine_pointed = vector.direction(pointed_thing.above, fine_pointed)
```

**Comment by Athozus** [comment]
> > Replacing `subtract` by `direction` causes strange behaviours. Notably different results while pressing `Sneak` or not pressing it on « normal » blocks.
> 
> Checked this, try with:
> 
> ```lua
> local pointed_thing_diff = vector.direction(pointed_thing.under, pointed_thing.above)
> ```
> 
> and
> 
> ```lua
> fine_pointed = vector.direction(pointed_thing.above, fine_pointed)
> ```
> 
> Notice that I've swapped arguments.
> 
> I'm not sure however if this is correct or not, didn't really think it through and it is likely that directions have been messed up either since beginning or since I've rewritten this thing for cable plate placement.

Still not very precise. I'm currently decomposing the algorithm because I think it can be 50% shorter.

File: technic/machines/register/cables.lua [hunk 2]
```diff
@@ -96,14 +96,16 @@ function technic.register_cable_plate(nodename, data)
...
 				local num = index < 0 and -index + 3 or index
 				local crtl = placer:get_player_control()
 				if (crtl.aux1 or crtl.sneak) and not (crtl.aux1 and crtl.sneak) and index ~= 0 then
 					local fine_pointed = minetest.pointed_thing_to_face_pos(placer, pointed_thing)
-					fine_pointed = vector.subtract(fine_pointed, pointed_thing.above)
-					fine_pointed[xyz[index < 0 and -index or index]] = nil
+					fine_pointed = vector.direction(pointed_thing.above,fine_pointed)
+					-- Normalize direction to prevent `xyz` index overflow with oversize nodes
+					index = (math.abs(index)-1)%3+1
+					fine_pointed[xyz[index]] = nil
```
Comment (S-S-X) [inline technic/machines/register/cables.lua:108]: If you do use `vector.direction` this normalization shouldn't be needed at all.
But still just using direction should be tested even while there's few automated tests. At least there's no tests for oversized nodes and while tests for normal nodes have fairly high coverage for different placements/directions/controls/angles those still aren't 100%.

I might do some manual testing around this, while it would be nice probably not going to add automated tests however.

Comment (S-S-X) [inline technic/machines/register/cables.lua:108]: By previous comment I mean renormalization shouldn't be needed if vector.direction is used (as pointed thing is already normalized).

I think this would remove redundant normalization:
```suggestion
					fine_pointed = vector.direction(pointed_thing.above,fine_pointed)
					fine_pointed[xyz[index < 0 and -index or index]] = nil
```

**Comment by S-S-X** [comment]
> EDIT 3 : So using Sneak can returns float coordinates. Interesting......

`minetest.pointed_thing_to_face_pos` is what returns float that points exact relative position on pointed node surface. This is used to find edges and change cable plate placement behavior (0.3 or closer to farthest node edge).
Cable plate placement is kind of overcomplicated but also allows placing in pretty much any orientation by looking at different position on node surface with sneak.

However, it also seems that pointed_thing can sometimes be diagonal with oversized nodes in which case resulting direction will be float even while positions are not.

Currently this does fix some placements but not all, those that this wont fix also can't be fixed with original deferred normalization (which in turn only fixes cases where aux1 is held, that is nodes with formspec or other node specific action).

So I'd recommend this approach as a base as it, at least in theory, should get few things right that were wrong before but it still needs some additional work.

Not sure if we could round/floor here, it isn't really that clear where plate should be placed when pointed_thing is diagonal.

**Comment by Athozus** [comment]
> > EDIT 3 : So using Sneak can returns float coordinates. Interesting......
> 
> `minetest.pointed_thing_to_face_pos` is what returns float that points exact relative position on pointed node surface. This is used to find edges and change cable plate placement behavior (0.3 or closer to farthest node edge). Cable plate placement is kind of overcomplicated but also allows placing in pretty much any orientation by looking at different position on node surface with sneak.
> 
> However, it also seems that pointed_thing can sometimes be diagonal with oversized nodes in which case resulting direction will be float even while positions are not.

Yes I noticed that one with some chat-debugging, so I'm with my paper (and `lua_api.md`) to think about a much faster solution than the usual long algorithms.

> Currently this does fix some placements but not all, those that this wont fix also can't be fixed with original deferred normalization (which in turn only fixes cases where aux1 is held, that is nodes with formspec or other node specific action). Normal placement, even while broken because of this, shouldn't however cause crash as it will just try to place a node that does not exist.
> 
> So I'd recommend this approach as a base as it, at least in theory, should get few things right that were wrong before but it still needs some additional work.
> 
> Not sure if we could round/floor here, it isn't really that clear where plate should be placed when pointed_thing is diagonal.

I tested with some `math.ceil` and `mail.floor`, but maybe the best solution is just to use `param2` ? I don't really understand the necessarily of using 6 node registrations for the same one.

**Comment by S-S-X** [comment]
> I tested with some `math.ceil` and `mail.floor`, but maybe the best solution is just to use `param2` ?

param2 is very complicated, wouldn't recommend bringing that here. Nodes do not follow conventions for this.

> I don't really understand the necessarily of using 6 node registrations for the same one.

Because of limitations of connected nodeboxes, those can't be rotated but are always static.

**Comment by Athozus** [comment]
@S-S-X note that it can be merged, the thing is fixed. The PR with a more simplistic determination of the pointed face would come later.

**Comment by OgelGames** [comment]
Could maybe use a raycast to get the pointed position, that's what I used for `omnidriver`'s pointed mode: https://github.com/OgelGames/omnidriver/blob/a7234fc27ad822e53bb8d3f7373d3651e58a3b49/modes/pointed.lua#L6-L20

**Comment by S-S-X** [comment]
>  it can be merged, the thing is fixed

The thing isn't fixed. The thing will crash in certain cases.

This does anyway fix some cases and prevents some crashes, but only when pointed thing under isn't diagonal to above node.

If merging this fast to fix crashes then I'd suggest adding check for diagonal pointed thing and just cancel placement before even trying to do anything. Then we could also close linked issue, atow this PR isn't really enough to close linked issue.

> Could maybe use a raycast to get the pointed position, that's what I used for omnidriver's pointed mode: > https://github.com/OgelGames/omnidriver/blob/a7234fc27ad822e53bb8d3f7373d3651e58a3b49/modes/pointed.lua#L6-L20

Not sure how this is supposed to change it, placement already does ray cast and we do already have node position. What we do not have is direction in remaining few corner cases.
Do you think this could actually help somehow in obtaining wanted direction in those corner cases?

**Comment by S-S-X** [comment]
@Athozus could just use something like this to cancel action for remaining corner cases, allow at most single axis but do not care how far it is:
```lua
			def.on_place = function(itemstack, placer, pointed_thing)
				count = 0
				for axis in pairs(xyz) do
					count = count + (pointed_thing.under[axis] == pointed_thing.above[axis] and 0 or 1)
					if count > 1 then
						return itemstack
					end
				end
```

**Comment by Athozus** [comment]
> @Athozus could just use something like this to cancel action for remaining corner cases, allow at most single axis but do not care how far it is:
> 
> ```lua
> def.on_place = function(itemstack, placer, pointed_thing)
> 	count = 0
> 	for axis in pairs(xyz) do
> 		count = count + (pointed_thing.under[axis] == pointed_thing.above[axis] and 0 or 1)
> 		if count > 1 then
> 			return itemstack
> 		end
> 	end
> ```
> 

This code works fine (I kept after that pre-condition the code I wrote upper). Maybe we should just returner the `cable_plate_1` instead of avoiding it ?

> Could maybe add comment too with link to this PR `https://github.com/mt-mods/technic/pull/358`

What do you exactly mean ? Should I add : ?
```lua
-- related to github.com/mt-mods/technic/pull/358
```

File: technic/machines/register/cables.lua [hunk 3]
```diff
@@ -96,32 +96,20 @@ function technic.register_cable_plate(nodename, data)
...
+				for axis in pairs(xyz) do
+					axis_count = axis_count + (pointed_thing.under[axis] == pointed_thing.above[axis] and 0 or 1)
+					if axis_count > 1 then
+						return itemstack
 					end
 				end
+
+				local pointed_thing_diff = vector.direction(pointed_thing.above, pointed_thing.under)
+				local dir = math.abs(pointed_thing_diff.x + 2*pointed_thing_diff.y + 3*pointed_thing_diff.z) -- 1, 2 or 3
+				local num = dir + 3/2*(1+pointed_thing_diff[dir]) -- dir + additional offset
```
Comment (S-S-X) [inline technic/machines/register/cables.lua:111]: What was this supposed to do and how exactly does it handle placement options?

For now it does fail significant portion of test cases and instead of fixing bug it seems to be an attempt to rework whole user facing placement behavior.

Comment (Athozus) [reply technic/machines/register/cables.lua:111]: * `pointed_thing_diff` : you know ;)
* `dir`: the previously index, but reinforced
  * x = +/- 1 returns 1
  * y = +/- 1 returns 2
  * z = +/-1 returns 3
* `num` : the number of the `cable_plate_num` model ; it's working like `y = ax+b`
  * `dir +` : because its keep that `b` which means the axis
  * `1+pointed_thing_diff[dir]` : 
    * returns 0 for x/y/z = -1
    * returns 2 for x/y/z = 1
  * `*3/2` : add this offset of 0 or 2, depending on the value

This is relatively short, and understandable, according to me.

Comment (S-S-X) [reply technic/machines/register/cables.lua:111]: It is but it is reworking whole placement behavior which in my opinion is not good thing to do.

Needs some more discussion about before going there. Bugs can be fixed without changing behavior, for that I'd of course give approval but for changing behavior without good enough reasoning reject from me.

**Review by S-S-X — CHANGES_REQUESTED** [review]
If going to make placement behavior completely different from what it was:
Update description and title, update tests and provide reasoning why new behavior is better for players than previous one.

If going to just fix crash then revert to original placement behavior but keep fixes (diagonal checks + vector.direction on 2 lines).

**Comment by Athozus** [comment]
Reverted to previous commit (work on that potentially for later).

**Comment by S-S-X** [comment]
> Reverted to previous commit (work on simplification attempt potentially for later).

This does still need that diagonal placement check, was also dropped while reverting: https://github.com/mt-mods/technic/pull/358#issuecomment-2041506832

**Review by S-S-X — APPROVED** [review]
Looks good now, should fix placement crash for all over sized support nodes.

* In some cases placement work correctly and probably how most would expect it to work.
* In some cases placement is prevented to not crash it, some of these could have valid position for placement but are very few special cases so it is better just skip placement for now.

These changes were tested a bit too.

**Comment by Athozus** [comment]
I rebased it, changes look fine. Ofc for this one a squash :sweat_smile: .

**Comment by S-S-X** [comment]
Another PR was merged so rebased again, most testing I did was exactly for these changes / current state and there's multiple automated tests confirming that most placements work like before. Should be good enough so merging this.
